CONFIG_ZMK_KEYBOARD_NAME="Quang"

# Bluetooth
CONFIG_BT=y
CONFIG_ZMK_BLE=y

# Pin (nice!nano có pin)
CONFIG_ZMK_BATTERY_REPORTING=y

# Tối ưu scan
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=5
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=5

# Tắt debug cho nhẹ
CONFIG_ZMK_LOG_LEVEL_INF=y
CONFIG_ZMK_LOG_LEVEL_DBG=n
